import type { Metadata } from 'next';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'DevCore',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/DevCoreWeb/assets/img/favicon.svg" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/all.min.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/animate.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/magnific-popup.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/meanmenu.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/swiper-bundle.min.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/nice-select.css" />
        <link rel="stylesheet" href="/DevCoreWeb/assets/css/style.css" />
      </head>
      <body>
        {children}

        <Script src="/DevCoreWeb/assets/js/jquery-3.7.1.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/viewport.jquery.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/bootstrap.bundle.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/jquery.nice-select.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/jquery.waypoints.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/jquery.counterup.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/swiper-bundle.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/jquery.meanmenu.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/jquery.magnific-popup.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/wow.min.js" strategy="beforeInteractive" />
        <Script src="/DevCoreWeb/assets/js/main.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
